In [2]:
import os 
import sys
import pandas as pd
import sksurv
import numpy as np

In [3]:
from sksurv.datasets import load_veterans_lung_cancer
data_X, data_y = load_veterans_lung_cancer()

In [4]:
data_X

,Age_in_years,Celltype,Karnofsky_score,Months_from_Diagnosis,Prior_therapy,Treatment
0,69.0,squamous,60.0,7.0,no,standard
1,64.0,squamous,70.0,5.0,yes,standard
2,38.0,squamous,60.0,3.0,no,standard
3,63.0,squamous,60.0,9.0,yes,standard
4,65.0,squamous,70.0,11.0,yes,standard
...,...,...,...,...,...,...
132,65.0,large,75.0,1.0,no,test
133,64.0,large,60.0,5.0,no,test
134,67.0,large,70.0,18.0,yes,test
135,65.0,large,80.0,4.0,no,test
136,37.0,large,30.0,3.0,no,test